name: "Publish Container Image"
on:
  push:
  workflow_dispatch: # 添加手动触发
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # 必须授权以推送镜像
    env:
      REPO_NAME: ${{ github.repository }}
      IMAGE_NAME: tailscale
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置小写镜像名称和版本
        run: |
          LOWER_NAME=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]')
          echo "LOWER_NAME=$LOWER_NAME" >> $GITHUB_ENV
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: 登录到 GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: 设置 QEMU 支持多架构
        uses: docker/setup-qemu-action@v3

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: 构建并推送 Docker 镜像
      #   uses: docker/build-push-action@v6
      #   with:
      #     file: Dockerfile
      #     context: .
      #     platforms: linux/amd64    #,linux/arm64 # 指定架构：x86_64 和 ARM64
      #     push: true
      #     tags: |
      #       ghcr.io/${{ env.LOWER_NAME }}:latest


      # - name: 构建并推送 derper Docker 镜像
      #   uses: docker/build-push-action@v6
      #   with:
      #     file: Dockerfile2
      #     context: .
      #     platforms: linux/amd64    #,linux/arm64 # 指定架构：x86_64 和 ARM64
      #     push: true
      #     tags: |
      #       ghcr.io/${{ env.LOWER_NAME }}:derper   

      - name: 构建并推送 Docker 镜像
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile3
          context: .
          platforms: linux/amd64    #,linux/arm64 # 指定架构：x86_64 和 ARM64
          push: true
          tags: |
            ghcr.io/${{ env.LOWER_NAME }}:beta   
        


      - uses: actions/delete-package-versions@v5
        with: 
          package-name: 'tailscale'
          package-type: 'container'
          min-versions-to-keep: 3
          delete-only-untagged-versions: 'true'